config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'welcome/index'

  resources :cards

  resources :cubes do
    resources :cube_cards#, :action => 'edit'
  end

  # this doesn't work because it still requires /cube_card/xx
  #resources :cube_cards, :path_prefix => 'cubes/:cube_id',

  resources :register, :controller => 'users', :action => 'new'
  resources :login, :controller => 'users', :action => 'login'
  #connect ':cubes/:cube_id/:cube_card_id', :action => 'show'
  #resources 'showcard/:cube_id/:cube_card_id', :controller => ['cubes', 'cube_cards'], :action => 'show'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :name, :set, :pokemontype, :stage, :rarity, :number, presence: true
  validates :hp, numericality: { only_integer: true }, allow_nil: true
  validates :retreat, numericality: { only_integer: true }, allow_nil: true
end

app/models/cube.rb
# encoding: utf-8
class Cube < ApplicationRecord
  has_many :cube_cards, :class_name => 'CubeCard'
  validates :name, length: { in: 3..30 }
  validates :private, inclusion: { in: ["1", "0"] }, on: :update
end

app/models/cube_card.rb
class CubeCard < ApplicationRecord
  belongs_to :cube
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password_digest, presence: true, length: {minimum: 6}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all
  end

  def new
    @card = Card.new
  end

  def edit
    @card = Card.find(params[:id])
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to @card
    else
      render 'new'
    end
  end

  def show
    @par = params
    @card = Pokemon::Card.where(page: 1).where(pageSize: 10).where(name: params[:id]).all
  end

  def update
    @card = Card.find(params[:id])

    if @card.update(card_params)
      redirect_to @card
    else
      render 'edit'
    end
  end

  def destroy
  end

  private
    def card_params
      params.require(:card).permit(:name, :set, :number, :pokemontype, :hp, :stage, :retreat, :rarity, :dtype, :image)
    end
end

app/controllers/cube_cards_controller.rb
class CubeCardsController < ApplicationController
  def create
    @cube = Cube.find(params[:cube_id])

    @cube_card = @cube.cube_cards.create(cube_card_params)
    redirect_to cube_path(@cube)
  end

  def edit
    @cube = Cube.find(params[:cube_id])
    @cube_card = @cube.cube_cards.find(params[:id])
  end

  def update
    @cube = Cube.find(params[:cube_id])
    @cube_card = @cube.cube_cards.find(params[:id])

    if @cube_card.update(cube_card_params)
      redirect_to @cube
    else
      render 'edit'
    end
  end

  def destroy
    @cube = Cube.find(params[:cube_id])
    @cube_card = @cube.cube_cards.find(params[:id])
    @cube_card.destroy
    redirect_to cube_path(@cube)
  end

  private
    def cube_card_params
      params.require(:cube_card).permit(:cube_id, :set_id, :card_number, :evolutionary_line)
      #params.require(:card)
    end
end

app/controllers/cubes_controller.rb
class CubesController < ApplicationController

  def index
    @cubes = Cube.all
    # Here's what will validate the item in the future
    #@cubes = Cube.where(owner_id: 1).all
  end

  def show
    @cube = Cube.find(params[:id])
    @cubecards = CubeCard.where(:cube_id => params[:id])
  end

  def new
    @cube = Cube.new
  end

  # Code for handling submitted form data for cubes/new/
  def create
    @cube = Cube.new(new_cube_params)
    @cube.private = "1"

    if @cube.save
      redirect_to @cube
    else
      render 'new'
    end
  end

  def edit
    @cube = Cube.find(params[:id])
  end

  def update
    @cube = Cube.find(params[:id])

    if params[:private] == "1"
      @cube.private = true
    else
      @cube.private = false
    end

    if @cube.update(cube_params)
      redirect_to @cube
    else
      render 'edit'
    end
  end

  def destroy
    @cube = Cube.find(params[:id])
    @cube.destroy

    redirect_to cubes_path
  end

  private
    # Strong Parameters validation
    def cube_params
      params.require(:cube).permit(:name, :description, :private)
    end

    def new_cube_params
      params.require(:cube).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def login
    @user = User.where('email = ? AND password_digest = ?', params[:email], params[:password_digest]).take
    if @user.valid?
      # do stuff
      
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password_digest)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def login
  end

  def register
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/cube_cards_helper.rb
module CubeCardsHelper
end

app/helpers/cubes_helper.rb
module CubesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/_add_card.html.erb
<p>
  Add a Card:
  <%= form_with(model: [ @cube, @cube.cube_cards.build ], local: true, id: "selection-card") do |form| %>
  <p>
    <%= form.collection_select(:set_id, Pokemon::Set.all, :code, :name) %>
    <%= form.number_field :card_number, in:1..300, step: 1, id: "card-id" %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <p>
    <img id="card-preview" alt="card preview" />
  </p>
  <% end %>
  <input type="text" id="card-search-field" /><button id="search-submit">Search</button>
  <div id="card-search">

  </div>
</p>
<%= javascript_include_tag :forced %>

app/views/cards/edit.html.erb
<%= form_with(model: @card) do |form| %>

  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, "error") %> prohibited
        this card from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :set %>
    <%= form.text_field :set %>
  </p>
  <p>
    <%= form.label :number %>
    <%= form.number_field :number, in: 1.0..500.0, step:1 %>
  </p>
  <p>
    <%= form.label :pokemontype %>
    <%= form.text_field :pokemontype %>
  </p>
  <p>
    <%= form.label :hp %>
    <%= form.number_field :hp, in: 0.0..500.0, step: 1 %>
  </p>
  <p>
    <%= form.label :stage %>
    <%= form.text_field :stage %>
  </p>
  <p>
    <%= form.label :retreat %>
    <%= form.number_field :retreat, in: 0.0..15.00, step: 1 %>
  </p>
  <p>
    <%= form.label :rarity %>
    <%= form.text_field :rarity %>
  </p>
  <p>
    <%= form.label :dtype %>
    <%= form.text_field :dtype %>
  </p>
  <p>
    <%= form.label :image %>
    <%= form.text_field :image %>
    (Note: you should link to the relative image, placed in assets/images)
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to "Back", cards_path %>

app/views/cards/index.html.erb
Listing all cards!

<table>
  <tr>
    <th>Name</th>
    <th>Set</th>
    <th>Number</th>
  </tr>

  <% @cards.each do |card| %>
    <tr>
      <td><%= card.name %></td>
      <td><%= card.set %></td>
      <td><%= card.number %></td>
      <td><%= link_to 'Show', card_path(card) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New card', new_card_path %>

app/views/cards/new.html.erb
<%= form_with scope: :card, url: cards_path, local: true do |form| %>

  <% if @card.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@card.errors.count, "error") %> prohibited
          this card from being saved:
        </h2>
        <ul>
          <% @card.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :set %>
    <%= form.text_field :set %>
  </p>
  <p>
    <%= form.label :number %>
    <%= form.number_field :number, in: 1.0..500.0, step:1 %>
  </p>
  <p>
    <%= form.label :pokemontype %>
    <%= form.text_field :pokemontype %>
  </p>
  <p>
    <%= form.label :hp %>
    <%= form.number_field :hp, in: 0.0..500.0, step: 1 %>
  </p>
  <p>
    <%= form.label :stage %>
    <%= form.text_field :stage %>
  </p>
  <p>
    <%= form.label :retreat %>
    <%= form.number_field :retreat, in: 0.0..15.00, step: 1 %>
  </p>
  <p>
    <%= form.label :rarity %>
    <%= form.text_field :rarity %>
  </p>
  <p>
    <%= form.label :dtype %>
    <%= form.text_field :dtype %>
  </p>
  <p>
    <%= form.label :image %>
    <%= form.text_field :image %>
    (Note: you should link to the relative image, placed in assets/images)
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/cards/show.html.erb
<div style="display: flex;flex-direction: column;">
  <%# @par.inspect %>
  <% @card.each do |card_inf| %>
    <!--<div>
      <p>Name: <%# @card.name %></p>
      <p>Set: <%# @card.set %></p>
      <p>Number: <%# @card.number %></p>
      <p>Type: <%# @card.pokemontype %></p>
      <p>Stage: <%# @card.stage %></p>
      <p>Rarity: <%# @card.rarity %></p>
      <%= card_inf.inspect %>
    </div>-->
    <div style="display: flex;">
        <button id="add-card-<%= card_inf.id %>">+</button>
        <div style="min-width: 100px;"><%= image_tag card_inf.image_url, alt: card_inf.name, style: "max-width: 100px; height: 130px;" %></div>
        <div style="line-height: 130px;"><%= card_inf.name + " (" + card_inf.id + ")" %></div>
        <script type="text/javascript">
          $("#add-card-<%= card_inf.id %>").click(function () {
            var n = "<%= card_inf.id %>".split("-");
            $("[name='cube_card[set_id]']").val(n[0]);
            $("#card-id").val(n[1]);
          });
        </script>
    </div>
  <% end %>
</div>

app/views/cube_cards/_cube_card.html.erb
<% card_inf = Pokemon::Card.find(cube_card.set_id.to_s + '-' + cube_card.card_number.to_s) %>
<fieldset>
  <legend><strong><%= card_inf.name %></strong></legend>
  <%
  if card_inf.nil?
    exit
  else
  %>
    <p><%= card_inf.image_url %></p>
    <p><%= image_tag card_inf.image_url, alt: card_inf.image_url %></p>
  <% end %>
  <%= link_to 'Remove', [cube_card.cube, cube_card], method: :delete  %>
</fieldset>

app/views/cube_cards/_cube_card2.html.erb
<h2>Cards</h2>
<% allcards = [] %>
<%
  # Build a model of cards to add, with all relevant information in place:
  def TypeObj
    return {
      "Pokémon" => {
        "MEGA" => [],
        "Level Up" => [],
        "EX" => [],
        "Restored" => [],
        "Stage 1" => [],
        "LEGEND" => [],
        "BREAK" => [],
        "Stage 2" => [],
        "Basic" => []
      },
      "Energy" => {
        "Special" => []
      },
      "Trainer" => {
        "Item" => [],
        "Supporter" => [],
        "Technical Machine" => [],
        "Rocket's Secret Machine" => [],
        "Stadium" => [],
        "BREAK" => [],
        "Pokémon Tool" => []
      }
    }
  end

  {
    "Colorless" => TypeObj(),
    "Dark" => TypeObj(),
    "Darkness" => TypeObj(),
    "Dragon" => TypeObj(),
    "Fairy" => TypeObj(),
    "Fighting" => TypeObj(),
    "Fire" => TypeObj(),
    "Grass" => TypeObj(),
    "Lightning" => TypeObj(),
    "Metal" => TypeObj(),
    "Psychic" => TypeObj(),
    "Water" => TypeObj()
  }
%>
<!--
  to do:
    Build a model of the cards to add, with all relative information in place. Then, read it out to the necessary fields. example:
    factored = {
      types: {
        "Colorless": {
          "Stage 1": [Pokemon::Card(Linoone), Pokemon::Card(Clefable)],
          "Stage 2": [],
          "Basic": [Pokemon::Card(Clefairy), Pokemon::Card(Zigzagoon)]
        },
        "Electric": {
          "Stage 1": [Pokemon::Card(Pikachu)]
        }
      }
    }

    Then, do a .each for factored.types as |typeset|
      <div/typeset.name>
      Then, typeset.each do |subtype|
        if subtype !empty
          <div/subtype.name>
          Then, subtype.each do |card|
            <linkto/card>
          e
        e
      e
    e
-->
<% @cube.cube_cards.each do |cube_card| %>
  <% allcards << [Pokemon::Card.find(cube_card.set_id + "-" + cube_card.card_number), [cube_card.cube, cube_card]] %>
<% end %>
<% Pokemon::Type.all.each  do |type| %>
  <%= content_tag :fieldset, style: "display: flex", class: type + "-set" do -%>
    <%= content_tag :legend, type + " Cards" %>
    <%= content_tag :div do -%>
      <% Pokemon::Subtype.all.each do |subtype| %>
        <%= content_tag :fieldset, style: "display: inline-flex; flex-direction: column" do -%>
          <%= content_tag :legend, subtype %>
          <% allcards.each do |card_inf| %>
            <% if subtype == card_inf[0].subtype && card_inf[0].types[0] == type %>
                <%= link_to card_inf[0].name, card_inf[1], data: { :image => card_inf[0].image_url }  %>
                <!--<= link_to 'Remove', [cube_card.cube, cube_card], method: :delete  %>-->
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/cube_cards/_cube_card3.html.erb
<%
  # Build a model of cards to add, with all relevant information in place:
  def TypeObj(type)
    # If the card is a trainer, it will have different subtypes
    if type == "Trainer"
      return {
        "Item" => [],
        "Supporter" => [],
        "Technical Machine" => [],
        "Rocket's Secret Machine" => [],
        "Stadium" => [],
        "Pokémon Tool" => [],
        "Special" => [],
        "Energy" => []
      }
    end

    # Default to the card being a Pokemon
    return {
      "Basic" => [],
      "Stage 1" => {
        "Basic" => [],
        "Stage 1" => []
      },
      "Stage 2" => {
        "Basic" => [],
        "Stage 1" => [],
        "Stage 2" => []
      },
      "Plus Line" => {
        "Restored" => [],
        "EX" => [],
        "Level Up" => [],
        "MEGA" => [],
        "LEGEND" => [],
        "BREAK" => []
      },
      "Trainer" => [],
    }
  end

  # This will influence the order in which cards are listed on
  #   the energy curve page
  typelist = [
    "Grass",
    "Fire",
    "Water",
    "Lightning",
    "Psychic",
    "Fighting",
    "Darkness",
    "Metal",
    "Fairy",
    "Dragon",
    "Colorless",
    "Trainer"
  ]

  # Add a case to this if the name of your type is discordant from
  #   what you want displayed as the description for it
  def process_subtype(name)
    if name == "Energy"
      name = "Special Energy"
    elsif name == "Special"
      name = "Ace-Spec"
    end

    return name
  end

  # Function for displaying the name of each evo line
  def process_evolutionary_line(name)
    if name == "Stage 1"
      name = "Stage 1 Line"
    elsif name == "Stage 2"
      name = "Stage 2 Line"
    elsif name == "Basic"
      name = "Basic Only"
    elsif name == "Trainer"
      name = "Trainer"
    else
      name = "Plus Line"
    end
  end

  # Determines what to display empty fields for, for legibility's sake.
  must_display = ["Basic", "Stage 1", "Stage 2", "Trainer", "Item", "Pokémon Tool", "Energy"]

  # typecount counts the number of cards in each type
  typecount = {}
  colors_object = {}

  # Assigns the card types to a hash that will serve as the HTML model
  typelist.each do |type|
    colors_object[type] = TypeObj(type)
    typecount[type] = 0
  end

  # Assigns the cards to the card types hashes from the last each...do
  @cube.cube_cards.each do |cube_card|
    if cube_card.set_id.blank? || cube_card.card_number.blank?
      cube_card.destroy
      puts "A critical error occurred: card present with no ID"
      exit
    end
    current_card = [Pokemon::Card.find(cube_card.set_id + "-" + cube_card.card_number), [cube_card.cube, cube_card]]
    # todo: do an if/else to make sure there is only one element in current_card[0].types

    # Special case for typeless trainers
    if current_card[0].types.blank?
      current_card[0].types = ["Trainer"]
    end

    # Keep track of the number of cards of each type to avoid performance sink
    typecount[current_card[0].types[0]] += 1

    # assign the card to the correct array
    if current_card[0].supertype == "Energy"
      colors_object[current_card[0].types[0]]["Energy"] << current_card
    else
      if ['other', 'stage 1', 'stage 2'].include?(current_card[1][1].evolutionary_line)
        if current_card[1][1].evolutionary_line == 'other'
          colors_object[current_card[0].types[0]]["Plus Line"][current_card[0].subtype] << current_card
        elsif current_card[1][1].evolutionary_line == 'stage 1'
          colors_object[current_card[0].types[0]]["Stage 1"][current_card[0].subtype] << current_card
        elsif current_card[1][1].evolutionary_line == 'stage 2'
          colors_object[current_card[0].types[0]]["Stage 2"][current_card[0].subtype] << current_card
        end
      else
        puts "\n\n\n\n" + current_card[0].types.inspect + "\n\n\n"
        if ['Basic', 'Trainer'].include?(current_card[0].subtype) || 'Trainer' == current_card[0].supertype
          colors_object[current_card[0].types[0]][current_card[0].subtype] << current_card
        else
          colors_object[current_card[0].types[0]][current_card[0].subtype][current_card[0].subtype] << current_card
        end
      end
    end
  end

  # Sort the cards in alphabetical order
=begin
  colors_object.each do |type,subtypes|
    subtypes.each do |subtype,cards_obj|
      if ['Trainer', 'Basic'].include? subtype
        colors_object[type][subtype] = colors_object[type][subtype].sort_by { |card| card[0].name.downcase }
      else
        cards_obj.each do |sub_subtype,sub_cards_obj|
          colors_object[type][subtype][sub_subtype] = colors_object[type][subtype][sub_subtype].sort_by { |card| card[0].name.downcase }
        end
      end
    end
  end
=end
%>
<% colors_object.each do |type,subtypes| %>
  <%= content_tag :fieldset, class: [type + "-set"] do %>
    <legend><%= type + " (" + typecount[type].to_s + ")" %></legend>
    <div class="type">
      <% subtypes.each do |subtype,cards_obj| %>
        <% if cards_obj.present? or must_display.include?(subtype)  %>
          <%= content_tag :div, class: "subtype" do %>
            <p><strong><%= process_evolutionary_line(subtype)
              # + " (" + cards_obj.size.to_s + ")"
             %></strong></p>
            <% if ['Basic'].include?(subtype) || ['Trainer', 'Energy'].include?(type) %>
              <ul>
                <% cards_obj.each do |my_card| %>
                  <li>
                    <%=
                      link_to my_card[0].name, 'javascript:void(0);', data: {
                        :image => my_card[0].image_url,
                        "high-res" => my_card[0].image_url_hi_res,
                        :edit => url_for([:edit] + my_card[1]),
                        "card-path" => url_for(my_card[1])
                      }, class: "cardlink"
                    %>
                  </li>
                <% end #cards_obj.each %>
              </ul>
            <% else %>
              <% cards_obj.each do |sub_subtype,sub_cards_obj| %>
                <% if sub_cards_obj.present? %>
                  <p><%= process_subtype(sub_subtype)
                  # + " (" + sub_cards_obj.size.to_s + ")"
                    %></p>
                  <ul>
                    <% sub_cards_obj.each do |my_card| %>
                      <li>
                        <%=
                          link_to my_card[0].name, 'javascript:void(0);', data: {
                            :image => my_card[0].image_url,
                            "high-res" => my_card[0].image_url_hi_res,
                            :edit => url_for([:edit] + my_card[1]),
                            "card-path" => url_for(my_card[1])
                          }, class: "cardlink"
                        %>
                      </li>
                    <% end #sub_cards_obj.each %>
                  </ul>
                <% end %>
              <% end #cards_obj.each %>
            <% end %>
          <% end #content_tag :div.subtype %>
        <% end %>
      <% end #subtypes.each %>
    </div>
  <% end #content_tag :fieldset %>
<% end %>

app/views/cube_cards/edit.html.erb
<h1>Edit Card</h1>

<%= form_with(model: [@cube, @cube_card], local: true, method: :patch) do |form| %>

  <% if @cube_card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@cube_card.errors.count, "error") %> prohibited
        this card from being saved:
      </h2>
      <ul>
        <% @cube_card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :image %><br>
    <%= form.text_field :image %>
  </p>

  <p>
    <%= form.label :tags %><br>
    <%= form.text_area :tags %>
  </p>

  <p class="evoline">
    <%= form.radio_button :evolutionary_line, "none" %>
    <%= form.label :evolutionary_line_none, "N/A" %><br>
    <%= form.radio_button :evolutionary_line, "basic" %>
    <%= form.label :evolutionary_line_basic, "Basic" %><br>
    <%= form.radio_button :evolutionary_line, "stage 1" %>
    <%= form.label :evolutionary_line_stage_1, "Stage 1" %><br>
    <%= form.radio_button :evolutionary_line, "stage 2" %>
    <%= form.label :evolutionary_line_stage_2, "Stage 2" %><br>
    <%= form.radio_button :evolutionary_line, "other" %>
    <%= form.label :evolutionary_line_other, "EX/GX/LEGEND/Other" %>
  </p>

  <p>
    <%= form.submit "Update card" %>
  </p>

<% end %>

<%= link_to 'Back', cube_path(@cube) %>

app/views/cubes/_cube_controls.html.erb
<h1><%= @cube.name %></h1>

<% if @cube.description %>
  <p>
    <strong>Description:</strong>
    <%= @cube.description %>
  </p>
<% end %>

<p>This cube
  <% if @cube.private == true %>
    <strong>is</strong>
  <% elsif @cube.private == false %>
    <strong>is not</strong>
  <% end %>
  private.
</p>

app/views/cubes/index.html.erb
<h1>Listing all Cubes <!-- authored by x --></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>

  <% @cubes.each do |cube| %>
    <tr>
      <td><%= cube.name %></td>
      <td><%= cube.description %></td>
      <td><%= link_to 'Show', cube_path(cube) %> | <%= link_to 'Edit', edit_cube_path(cube) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New cube', new_cube_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokecube</title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/login.html.erb
Login Page

app/views/welcome/register.html.erb
Registration Page